
-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- Users table (extends Supabase auth.users)
create table if not exists public.users (
  id uuid references auth.users on delete cascade primary key,
  email text unique not null,
  name text,
  role text check (role in ('Candidate', 'Employer', 'Agent', 'Admin')),
  mobile text,
  city text,
  state text,
  linkedin_url text,
  work_authorization text,
  status text default 'Active',
  ai_config jsonb default '{}'::jsonb,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS for users
alter table public.users enable row level security;

-- Jobs table
create table if not exists public.jobs (
  id bigint generated by default as identity primary key,
  title text not null,
  employer text not null,
  location text,
  salary text,
  type text,
  description text,
  requirements text[],
  status text default 'Active',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS for jobs
alter table public.jobs enable row level security;

-- Candidates (Applications) table
create table if not exists public.candidates (
  id bigint generated by default as identity primary key,
  user_id uuid references public.users(id),
  "jobId" bigint references public.jobs(id),
  name text,
  role text,
  status text default 'Applied',
  dob text,
  "resumeSummary" text,
  source text,
  interview_config jsonb default '{}'::jsonb,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS for candidates
alter table public.candidates enable row level security;

-- Placements table
create table if not exists public.placements (
  id bigint generated by default as identity primary key,
  "candidateId" bigint references public.candidates(id),
  "jobId" bigint references public.jobs(id),
  status text,
  "startDate" date,
  salary text,
  fee text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS for placements
alter table public.placements enable row level security;

-- Resumes table
create table if not exists public.resumes (
  id bigint generated by default as identity primary key,
  user_id uuid references public.users(id),
  version int default 1,
  parsed_data jsonb,
  is_current boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS for resumes
alter table public.resumes enable row level security;

-- Interviews table (for InterviewStore)
create table if not exists public.interviews (
  id text primary key,
  "candidateId" text,
  status text,
  "startTime" timestamp with time zone,
  "endTime" timestamp with time zone,
  transcript text,
  score numeric,
  feedback text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS for interviews
alter table public.interviews enable row level security;

-- Rooms table (for RoomRegistry)
create table if not exists public.rooms (
  id text primary key,
  status text,
  "createdAt" timestamp with time zone default timezone('utc'::text, now()),
  "lastActive" timestamp with time zone,
  metadata jsonb default '{}'::jsonb
);

-- Enable RLS for rooms
alter table public.rooms enable row level security;

-- Audit Logs table
create table if not exists public.audit_logs (
  id uuid default uuid_generate_v4() primary key,
  action text not null,
  resource_type text,
  resource_id text,
  details jsonb,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS for audit_logs
alter table public.audit_logs enable row level security;

-- RLS Policies (Basic examples - refine for production)

-- Users: Users can read their own profile. Employers/Agents can read Candidate profiles.
create policy "Users can read own profile" on public.users for select using (auth.uid() = id);
create policy "Employers/Agents can read candidates" on public.users for select using (role = 'Candidate' and exists (select 1 from public.users where id = auth.uid() and role in ('Employer', 'Agent')));
create policy "Users can update own profile" on public.users for update using (auth.uid() = id);
create policy "Service role can do everything on users" on public.users using (true) with check (true); -- For backend

-- Jobs: Everyone can read active jobs. Employers/Agents can create/update.
create policy "Everyone can read jobs" on public.jobs for select using (true);
create policy "Employers/Agents can insert jobs" on public.jobs for insert with check (exists (select 1 from public.users where id = auth.uid() and role in ('Employer', 'Agent')));
create policy "Employers/Agents can update jobs" on public.jobs for update using (exists (select 1 from public.users where id = auth.uid() and role in ('Employer', 'Agent')));

-- Candidates: Users can read their own applications. Employers/Agents can read all.
create policy "Users can read own applications" on public.candidates for select using (auth.uid() = user_id);
create policy "Employers/Agents can read all applications" on public.candidates for select using (exists (select 1 from public.users where id = auth.uid() and role in ('Employer', 'Agent')));
create policy "Users can insert applications" on public.candidates for insert with check (auth.uid() = user_id);
create policy "Employers/Agents can update applications" on public.candidates for update using (exists (select 1 from public.users where id = auth.uid() and role in ('Employer', 'Agent')));

-- Resumes: Users can read/insert their own resumes. Employers/Agents can read.
create policy "Users can read own resumes" on public.resumes for select using (auth.uid() = user_id);
create policy "Employers/Agents can read resumes" on public.resumes for select using (exists (select 1 from public.users where id = auth.uid() and role in ('Employer', 'Agent')));
create policy "Users can insert resumes" on public.resumes for insert with check (auth.uid() = user_id);

-- Interviews/Rooms/AuditLogs: Mostly backend managed, but allow read for relevant roles if needed.
-- For now, relying on Service Role for backend operations.
